### ISSUE TITLE
Problem with importing lopq package on windows

### ISSUE THREAD

**Issue by ivan-marroquin** [yahoo/lopq#20]
Hi!

I have a windows 10 machine with Python 3.6.5. I ran the command 'pip install lopq", the installation ran successfully (see below)

C:\Users\IMarroquin\Documents\My_Python_Scripts\MLP\Well_8_to_five_wells\Independent_Scripts\Big_Data_For_Paradise>pip install lopq
Collecting lopq
  Downloading https://files.pythonhosted.org/packages/79/f9/d00a4944cf52688f112699ac99d6c86b11b865e054055014ad6d3d2cb768/lopq-1.0.35.tar.gz
Requirement already satisfied: protobuf>=2.6 in c:\temp\python\python36\lib\site-packages (from lopq)
Requirement already satisfied: numpy>=1.9 in c:\temp\python\python36\lib\site-packages (from lopq)
Requirement already satisfied: scipy>=0.14 in c:\temp\python\python36\lib\site-packages (from lopq)
Requirement already satisfied: scikit-learn>=0.15 in c:\temp\python\python36\lib\site-packages (from lopq)
Collecting lmdb>=0.87 (from lopq)
  Downloading https://files.pythonhosted.org/packages/cb/31/5be8f436b56733d9e69c721c358502f4d77b627489a459978686be7db65f/lmdb-0.94.tar.gz (4.0MB)
    100% |████████████████████████████████| 4.0MB 296kB/s
Requirement already satisfied: six>=1.9 in c:\temp\python\python36\lib\site-packages (from protobuf>=2.6->lopq)
Requirement already satisfied: setuptools in c:\temp\python\python36\lib\site-packages (from protobuf>=2.6->lopq)
Building wheels for collected packages: lopq, lmdb
  Running setup.py bdist_wheel for lopq ... done
  Stored in directory: C:\Users\IMarroquin\AppData\Local\pip\Cache\wheels\78\57\c6\1e56da35f08e349d6b3b7d7c495b70e0a1173db2f9ac289722
  Running setup.py bdist_wheel for lmdb ... done
  Stored in directory: C:\Users\IMarroquin\AppData\Local\pip\Cache\wheels\57\40\51\3fe10a4a559a91352579a27cbcca490f279bacb54209713c4b
Successfully built lopq lmdb
Installing collected packages: lmdb, lopq
Successfully installed lmdb-0.94 lopq-1.0.0
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

When I run python from a DOS console, and then I used one of these commands:
a) import lopq
b) from lopq import LOPQModel, LOPQSearcher

I get this error message:

  File "C:\Temp\Python\Python36\lib\site-packages\lopq\__init__.py", line 3, in <module>
    import model
ModuleNotFoundError: No module named 'model'

Any suggestions?

Many thanks,

Ivan

**Comment by ivan-marroquin** [comment]
Hi,

I installed the package on an Ubuntu 18.04 with Python 3.6.5. 

I still got the same issue.

Kind regards,
Ivan

**Comment by KuenstlicheIntelligenz** [comment]
Did you solved it? I saw a print withouht braces, i guess its a python 2 library

**Comment by ivan-marroquin** [comment]
I am using Python 3.6.5 and still have the issue

**Comment by seth814** [comment]
I also attempted on Ubuntu 18.04 and Python 3.6.5. Same issue. Installed a virtual env for Python 2.7 and was able to run everything.

**Comment by mohamed-ali** [comment]
Hi, I got the same issue on Mac, and ubuntu. 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/lopq/__init__.py", line 3, in <module>
    import model
ModuleNotFoundError: No module named 'model'
```
