### ISSUE TITLE
HELP! Exception when data.unpersist()

### ISSUE THREAD

**Issue by xhappy** [yahoo/lopq#22]
Hello,

This issue has blocked me. And I don't know how to solve it, so ask for help here.

Traceback (most recent call last):
  File "train_model.py", line 417, in <module>
    subs = train_subquantizers(sc, data, args.M, args.subquantizer_clusters, model, seed=args.seed)
  File "train_model.py", line 227, in train_subquantizers
    data.unpersist()
  File "/mnt/dfs/11/yarn/local/usercache/algo/appcache/application_1550790374016_973847/container_e66_1550790374016_973847_02_000001/pyspark.zip/pyspark/rdd.py", line 251, in unpersist
  File "/mnt/dfs/11/yarn/local/usercache/algo/appcache/application_1550790374016_973847/container_e66_1550790374016_973847_02_000001/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/mnt/dfs/11/yarn/local/usercache/algo/appcache/application_1550790374016_973847/container_e66_1550790374016_973847_02_000001/py4j-0.10.3-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o261.unpersist.
: org.apache.spark.SparkException: Exception thrown in awaitResult

**Comment by pumpikano** [comment]
I haven't run this code in years, as I no longer work for Yahoo, so I'm sorry to say that I can't be of much help. One thing that I am unsure of is whether this code is still compatible with the latest version of Spark, so this could be a source of the issue.
