### ISSUE TITLE
Exception occurred when copy model file to HDFS

### ISSUE THREAD

**Issue by xhappy** [yahoo/lopq#23]
Starting rotation fitting for split 1
Saving pickle to temp file...
Copying pickle file to hdfs...
hdfs:///user/algo/lopq/model/
Traceback (most recent call last):
  File "train_model.py", line 426, in <module>
    save_hdfs_pickle(model, args.model_pkl)
  File "train_model.py", line 245, in save_hdfs_pickle
    copy_to_hdfs(f, pkl_path)
  File "train_model.py", line 266, in copy_to_hdfs
    subprocess.call(['hadoop', 'fs', '-put', f.name, hdfs_path])
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
End of LogType:stdout

**Comment by pumpikano** [comment]
Sorry I can't be of much help here. To me it seems that there is some issue with the HDFS command executed in `subprocess.call(['hadoop', 'fs', '-put', f.name, hdfs_path])`.
